train_image: forrest_preprocess/sub-01/ses-movie/output/sub-01_ses-movie_task-movie_run-1_bold_resample_volregA_antswarp.nii.gz
train_x_fixation: train_test_data/subject_1_run_1_median_x.csv
train_y_fixation: train_test_data/subject_1_run_1_median_y.csv
train_x_std: train_test_data/x_std_run_1.txt
train_y_std: train_test_data/y_std_run_1.txt
test_image: forrest_preprocess/sub-01/ses-movie/output/sub-01_ses-movie_task-movie_run-3_bold_resample_volregA_antswarp.nii.gz
test_target_x: train_test_data/test_data/subject_1_run_3_true_x.csv
test_target_y: train_test_data/test_data/subject_1_run_3_true_y.csv
eye_mask: PEER_eye_2mm_r30.nii.gz
output_name: results_subject_1_run3.csv
